### ISSUE TITLE
crash on pixel3 xl android 11

### ISSUE THREAD

**Issue by HuixingWong** [skydoves/Pokedex-AR#1]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.WindowInsetsController com.android.internal.policy.DecorView.getWindowInsetsController()' on a null object reference
        at com.android.internal.policy.PhoneWindow.getInsetsController(PhoneWindow.java:3880)
        at com.skydoves.pokedexar.extensions.ActivityExtensionsKt.applyFullScreenWindow(ActivityExtensions.kt:31)
        at com.skydoves.pokedexar.ui.scene.SceneActivity.onCreate(SceneActivity.kt:44)

**Comment by skydoves** [comment]
Hi, @HuixingWong 
Thanks for your issue! It is fixed just now. :)

**Comment by HuixingWong** [comment]
> Hi, @HuixingWong
> Thanks for your issue! It is fixed just now. :)

I just tried to fix it but I don't understand why those lines of code crashed even if add null checked ， you  deleted those lines of code 😂
